#!/usr/bin/env python3
"""Emit one or more SQL++ bulk-load statements for all *.json files in a directory.

Supports two AsterixDB syntaxes (same ``nc_host://absolute_path`` URIs, comma-separated
when there are multiple shards):

- **load (default):** ``LOAD DATASET ... USING localfs (("path"="..."), ("format"="json"));``
- **copy:** ``COPY ... FROM localfs path ('...') with {'format':'json'};`` — use
  ``--syntax copy`` if your cluster/docs use this form (equivalent bulk load for many setups).

**Node Controller paths:** Each path segment in the URI must exist on the machine that
serves ``localfs`` (often the host in ``--nc-host``). Use ``--remote-base`` when files live
under a different absolute path on the NC than on the client.

Usage (then POST with load_ddl.py, which prepends ``USE`` per request)::

  python scripts/asterix/generate_json_dir_load_sqlpp.py \\
    --json-dir /data/tweets/json \\
    --dataset tweetsdatasetE \\
    --dataverse tweetverseembedding256file4 \\
    --nc-host 10.16.229.101 \\
    --syntax copy \\
    --out /tmp/tweets_load.sqlpp

  python scripts/asterix/load_ddl.py --url http://10.16.229.101:19002/query/service \\
    --dataverse tweetverseembedding256file4 --file /tmp/tweets_load.sqlpp
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _uris_for_files(
    files: list[Path],
    nc_host: str,
    remote_base: Path | None,
    json_dir: Path,
) -> list[str]:
    """Build nc_host://absolute_path URIs for localfs (POSIX slashes in path)."""
    uris: list[str] = []
    for f in files:
        f = f.resolve()
        if remote_base is not None:
            try:
                rel = f.relative_to(json_dir.resolve())
            except ValueError:
                rel = Path(f.name)
            remote_path = (remote_base / rel).resolve()
            path_str = remote_path.as_posix()
        else:
            path_str = f.as_posix()
        uris.append(f"{nc_host}://{path_str}")
    return uris


def _emit_bulk_statement(syntax: str, dataset: str, path_val: str) -> str:
    """Single LOAD DATASET or COPY FROM localfs line for one comma-separated path list."""
    if syntax == "copy":
        return (
            f"COPY {dataset} FROM localfs path ('{path_val}') "
            f"with {{'format':'json'}};"
        )
    return (
        f'LOAD DATASET {dataset} USING localfs (("path"="{path_val}"), ("format"="json"));'
    )


def _dataset_load_statements(
    syntax: str,
    dataset: str,
    uris: list[str],
    max_uris_per_statement: int | None,
) -> list[str]:
    """One or more bulk-load lines; split if max_uris_per_statement is set."""
    if not uris:
        return []
    if max_uris_per_statement is None or max_uris_per_statement <= 0:
        chunks = [uris]
    else:
        n = max_uris_per_statement
        chunks = [uris[i : i + n] for i in range(0, len(uris), n)]
    stmts: list[str] = []
    for i, chunk in enumerate(chunks):
        path_val = ",".join(chunk)
        head = (
            f"-- Load part {i + 1} of {len(chunks)} (same dataset)\n"
            if len(chunks) > 1
            else ""
        )
        stmts.append(head + _emit_bulk_statement(syntax, dataset, path_val))
    return stmts


def build_json_dir_load_sqlpp(
    json_dir: Path,
    dataset: str,
    dataverse: str,
    nc_host: str,
    *,
    syntax: str = "load",
    remote_base: Path | None = None,
    max_uris_per_load: int = 0,
) -> str:
    """
    Build full .sqlpp text (USE, bulk load statement(s), ANALYZE) for a flat *.json directory.
    Raises FileNotFoundError / ValueError if json_dir is invalid or has no *.json files.
    """
    json_dir = json_dir.expanduser().resolve()
    if not json_dir.is_dir():
        raise FileNotFoundError(f"not a directory: {json_dir}")

    files = sorted(json_dir.glob("*.json"))
    files = [f for f in files if f.is_file()]
    if not files:
        raise ValueError(f"no *.json files in {json_dir}")

    rb = remote_base.expanduser().resolve() if remote_base else None
    uris = _uris_for_files(files, nc_host.strip(), rb, json_dir)
    max_n = max_uris_per_load if max_uris_per_load > 0 else None
    body_stmts = _dataset_load_statements(syntax, dataset, uris, max_n)

    lines: list[str] = [
        "-- Generated by generate_json_dir_load_sqlpp.py",
        f"USE {dataverse};",
        "",
    ]
    lines.extend(body_stmts)
    lines.append("")
    lines.append(f"ANALYZE DATASET {dataset};")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate LOAD DATASET or COPY FROM localfs (JSON) for *.json in a directory",
        epilog=(
            "Output is a .sqlpp file suitable for scripts/asterix/load_ddl.py. "
            "load_ddl.py prepends USE <dataverse> to each statement because HTTP POST "
            "does not persist USE across requests."
        ),
    )
    p.add_argument(
        "--json-dir",
        required=True,
        type=Path,
        help="Directory containing *.json shard files",
    )
    p.add_argument(
        "--dataset",
        required=True,
        help="Target dataset name (must match CREATE DATASET)",
    )
    p.add_argument(
        "-D",
        "--dataverse",
        required=True,
        metavar="NAME",
        help="Dataverse name for USE line",
    )
    p.add_argument(
        "--nc-host",
        required=True,
        help="Host in localfs URIs (Node Controller host for localfs)",
    )
    p.add_argument(
        "--syntax",
        choices=("load", "copy"),
        default="load",
        help="SQL form: load=LOAD DATASET USING localfs (default), copy=COPY FROM localfs path",
    )
    p.add_argument(
        "--remote-base",
        type=Path,
        default=None,
        help=(
            "If set, URIs use nc_host://REMOTE_BASE/relative_path where relative_path is "
            "relative to --json-dir (for files staged on NC under REMOTE_BASE)"
        ),
    )
    p.add_argument(
        "--max-uris-per-load",
        type=int,
        default=0,
        metavar="N",
        help="If > 0, split into multiple statements with at most N URIs each "
        "(avoids very long single statements)",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Write SQL to this file (default: stdout)",
    )
    args = p.parse_args()

    remote_base = args.remote_base.expanduser().resolve() if args.remote_base else None

    try:
        text = build_json_dir_load_sqlpp(
            args.json_dir,
            args.dataset,
            args.dataverse,
            args.nc_host,
            syntax=args.syntax,
            remote_base=remote_base,
            max_uris_per_load=args.max_uris_per_load,
        )
    except (FileNotFoundError, ValueError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    if args.out:
        args.out.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
