#!/usr/bin/env python3
"""Emit LOAD DATASET SQL++ with comma-separated host://absolute_path URIs per *.json shard.

Scans output_dir/<dataset>/*.json (docgen layout). Run from ch2driver/pytpcc, then:
  python scripts/asterix/load_ddl.py --url http://127.0.0.1:19002/query/service --file /tmp/ch2_load.sqlpp
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Must match CREATE DATASET names in ddl/asterix/ch2pp_bench.sqlpp
DATASETS = [
    "warehouse",
    "district",
    "customer",
    "stock",
    "orders",
    "neworder",
    "history",
    "item",
    "supplier",
    "nation",
    "region",
]


def _uris_in_dir(d: Path, nc_host: str) -> list[str]:
    files = sorted(d.glob("*.json"))
    uris = []
    for f in files:
        if not f.is_file():
            continue
        uris.append(f"{nc_host}://{f.resolve()}")
    return uris


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate Asterix LOAD DATASET statements from docgen JSON layout"
    )
    p.add_argument(
        "--output-dir",
        required=True,
        type=Path,
        help="Docgen root (same as [asterix] output_dir)",
    )
    p.add_argument(
        "--nc-host",
        default="127.0.0.1",
        help="Host in localfs URIs (must match NC used for localfs)",
    )
    p.add_argument(
        "-D",
        "--dataverse",
        default="bench",
        metavar="NAME",
        help="Dataverse in generated USE (match [asterix] dataverse and DDL)",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Write SQL to this file (default: stdout)",
    )
    args = p.parse_args()

    root = args.output_dir.expanduser().resolve()
    if not root.is_dir():
        print(f"error: not a directory: {root}", file=sys.stderr)
        return 1

    lines: list[str] = [
        "-- Generated by generate_load_sqlpp.py — one LOAD per dataset, all *.json shards in path=",
        f"USE {args.dataverse};",
        "",
    ]

    loaded: list[str] = []
    for name in DATASETS:
        d = root / name
        if not d.is_dir():
            print(f"warning: skip {name}: missing directory {d}", file=sys.stderr)
            continue
        uris = _uris_in_dir(d, args.nc_host)
        if not uris:
            print(f"warning: skip {name}: no *.json in {d}", file=sys.stderr)
            continue
        path_val = ",".join(uris)
        lines.append(
            f'LOAD DATASET {name} USING localfs (("path"="{path_val}"), ("format"="json"));'
        )
        loaded.append(name)

    if not loaded:
        print("error: no datasets to load (no *.json found)", file=sys.stderr)
        return 1

    lines.append("")
    for name in loaded:
        lines.append(f"ANALYZE DATASET {name};")

    text = "\n".join(lines) + "\n"

    if args.out:
        args.out.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
