#!/usr/bin/env python3
"""Emit LOAD DATASET or COPY FROM localfs SQL++ — **one statement per ``*.json`` shard file**.

Scans output_dir/<dataset>/*.json (docgen layout). Run from ch2driver/pytpcc, then:
  python scripts/asterix/load_ddl.py --url http://127.0.0.1:19002/query/service --file /tmp/ch2_load.sqlpp

Use ``--syntax copy`` for ``COPY <dataset> FROM localfs path ('host://path') with {'format':'json'};``
per file. Default is ``LOAD DATASET ... USING localfs`` per file.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Must match CREATE DATASET names in ddl/asterix/ch2pp_bench.sqlpp
DATASETS = [
    "warehouse",
    "district",
    "customer",
    "stock",
    "orders",
    "neworder",
    "history",
    "item",
    "supplier",
    "nation",
    "region",
]


def _uris_in_dir(d: Path, nc_host: str) -> list[str]:
    files = sorted(d.glob("*.json"))
    uris = []
    for f in files:
        if not f.is_file():
            continue
        uris.append(f"{nc_host}://{f.resolve().as_posix()}")
    return uris


def _emit_bulk_statement(syntax: str, name: str, single_uri: str) -> str:
    if syntax == "copy":
        return (
            f"COPY {name} FROM localfs path ('{single_uri}') "
            f"with {{'format':'json'}};"
        )
    return (
        f'LOAD DATASET {name} USING localfs (("path"="{single_uri}"), ("format"="json"));'
    )


def build_ch2_docgen_load_sqlpp(
    output_dir: Path,
    nc_host: str,
    dataverse: str,
    syntax: str = "load",
) -> str:
    """
    Build .sqlpp text for all CH2++ docgen datasets under ``output_dir/<name>/*.json``.
    Same layout as ``generate_load_sqlpp.py`` CLI. Raises if no JSON shards found.
    """
    root = output_dir.expanduser().resolve()
    if not root.is_dir():
        raise FileNotFoundError(f"not a directory: {root}")

    lines: list[str] = [
        "-- Generated by generate_load_sqlpp.py — one LOAD/COPY per *.json shard file",
        f"USE {dataverse};",
        "",
    ]

    loaded: list[str] = []
    for name in DATASETS:
        d = root / name
        if not d.is_dir():
            print(f"warning: skip {name}: missing directory {d}", file=sys.stderr)
            continue
        uris = _uris_in_dir(d, nc_host)
        if not uris:
            print(f"warning: skip {name}: no *.json in {d}", file=sys.stderr)
            continue
        for uri in uris:
            lines.append(_emit_bulk_statement(syntax, name, uri))
        loaded.append(name)

    if not loaded:
        raise ValueError(
            f"no datasets to load under {root} (need subdirs {', '.join(DATASETS)} with *.json)"
        )

    lines.append("")
    for name in loaded:
        lines.append(f"ANALYZE DATASET {name};")

    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate Asterix LOAD DATASET statements from docgen JSON layout"
    )
    p.add_argument(
        "--output-dir",
        required=True,
        type=Path,
        help="Docgen root (same as [asterix] output_dir)",
    )
    p.add_argument(
        "--nc-host",
        default="127.0.0.1",
        help="Host in localfs URIs (must match NC used for localfs)",
    )
    p.add_argument(
        "-D",
        "--dataverse",
        default="bench",
        metavar="NAME",
        help="Dataverse in generated USE (match [asterix] dataverse and DDL)",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Write SQL to this file (default: stdout)",
    )
    p.add_argument(
        "--syntax",
        choices=("load", "copy"),
        default="load",
        help="SQL form: load=LOAD DATASET USING localfs (default), copy=COPY FROM localfs path",
    )
    args = p.parse_args()

    root = args.output_dir.expanduser().resolve()
    try:
        text = build_ch2_docgen_load_sqlpp(
            root,
            args.nc_host,
            args.dataverse,
            syntax=args.syntax,
        )
    except (FileNotFoundError, ValueError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    if args.out:
        args.out.write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
